PREFIX ex: <https://ameniki.github.io/japan-cultural-heritage-lod/japan-cultural-heritage.ttl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?name ?year
WHERE {
  ?site a ex:WorldHeritageSite ;
        rdfs:label ?name ;
        ex:registrationYear ?year .
}
ORDER BY ?year
